fpaths:
  uploads: public/images
  static: public
collections_config:
  posts:
    path: src/content/blog
    output: false
    icon: notes
    disable_add: false
    disable_add_folder: false
    disable_file_actions: false
timezone: Etc/UTC

_inputs:
  src: 
    type: images
